//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 04:08:48 PM YEKT 
//


package com.sankdev.edbind;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Authorized Claim Authors List.
 * 
 * <p>Java class for AuthorizedClaimAuthors complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuthorizedClaimAuthors"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AuthorizedClaimAuthorsList" type="{urn:cbr-ru:ed:v2.0}AuthorizedClaimAuthorsList" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthorizedClaimAuthors", propOrder = {
    "authorizedClaimAuthorsList"
})
public class AuthorizedClaimAuthors {

    @XmlElement(name = "AuthorizedClaimAuthorsList", required = true)
    protected List<AuthorizedClaimAuthorsList> authorizedClaimAuthorsList;

    /**
     * Gets the value of the authorizedClaimAuthorsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the authorizedClaimAuthorsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorizedClaimAuthorsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorizedClaimAuthorsList }
     * 
     * 
     */
    public List<AuthorizedClaimAuthorsList> getAuthorizedClaimAuthorsList() {
        if (authorizedClaimAuthorsList == null) {
            authorizedClaimAuthorsList = new ArrayList<AuthorizedClaimAuthorsList>();
        }
        return this.authorizedClaimAuthorsList;
    }

}
