//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Condition Parameters.
 * 
 * <p>Java class for CoverFundsSchemeParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoverFundsSchemeParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CoverSum" type="{urn:cbr-ru:ed:v2.0}CoverSum" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ParticipantToBeNotified" type="{urn:cbr-ru:ed:leaftypes:v2.0}EDDrawerIDType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoverFundsSchemeParameters", propOrder = {
    "coverSum"
})
public class CoverFundsSchemeParameters {

    @XmlElement(name = "CoverSum")
    protected CoverSum coverSum;
    @XmlAttribute(name = "ParticipantToBeNotified")
    protected String participantToBeNotified;

    /**
     * Gets the value of the coverSum property.
     * 
     * @return
     *     possible object is
     *     {@link CoverSum }
     *     
     */
    public CoverSum getCoverSum() {
        return coverSum;
    }

    /**
     * Sets the value of the coverSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverSum }
     *     
     */
    public void setCoverSum(CoverSum value) {
        this.coverSum = value;
    }

    /**
     * Gets the value of the participantToBeNotified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipantToBeNotified() {
        return participantToBeNotified;
    }

    /**
     * Sets the value of the participantToBeNotified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipantToBeNotified(String value) {
        this.participantToBeNotified = value;
    }

}
