//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 04:08:48 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Departmental Information (fields 101, 104-110).
 * 
 * <p>Java class for DepartmentalInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DepartmentalInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="DrawerStatus" type="{urn:cbr-ru:ed:leaftypes:v2.0}DrawerStatusCodeTextType" /&gt;
 *       &lt;attribute name="CBC" type="{urn:cbr-ru:ed:leaftypes:v2.0}CBCIDTextType" /&gt;
 *       &lt;attribute name="OKATO" type="{urn:cbr-ru:ed:leaftypes:v2.0}OKATOIDTextType" /&gt;
 *       &lt;attribute name="PaytReason" type="{urn:cbr-ru:ed:leaftypes:v2.0}TaxPaytReasonCodeTextType" /&gt;
 *       &lt;attribute name="TaxPeriod" type="{urn:cbr-ru:ed:leaftypes:v2.0}TaxPeriodCodeTextType" /&gt;
 *       &lt;attribute name="DocNo" type="{urn:cbr-ru:ed:leaftypes:v2.0}TaxDocIDTextType" /&gt;
 *       &lt;attribute name="DocDate" type="{urn:cbr-ru:ed:leaftypes:v2.0}TaxDocDateCodeTextType" /&gt;
 *       &lt;attribute name="TaxPaytKind" type="{urn:cbr-ru:ed:leaftypes:v2.0}TaxPaytKindCodeTextType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DepartmentalInfo")
public class DepartmentalInfo {

    @XmlAttribute(name = "DrawerStatus")
    protected String drawerStatus;
    @XmlAttribute(name = "CBC")
    protected String cbc;
    @XmlAttribute(name = "OKATO")
    protected String okato;
    @XmlAttribute(name = "PaytReason")
    protected String paytReason;
    @XmlAttribute(name = "TaxPeriod")
    protected String taxPeriod;
    @XmlAttribute(name = "DocNo")
    protected String docNo;
    @XmlAttribute(name = "DocDate")
    protected String docDate;
    @XmlAttribute(name = "TaxPaytKind")
    protected String taxPaytKind;

    /**
     * Gets the value of the drawerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawerStatus() {
        return drawerStatus;
    }

    /**
     * Sets the value of the drawerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawerStatus(String value) {
        this.drawerStatus = value;
    }

    /**
     * Gets the value of the cbc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBC() {
        return cbc;
    }

    /**
     * Sets the value of the cbc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBC(String value) {
        this.cbc = value;
    }

    /**
     * Gets the value of the okato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKATO() {
        return okato;
    }

    /**
     * Sets the value of the okato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKATO(String value) {
        this.okato = value;
    }

    /**
     * Gets the value of the paytReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaytReason() {
        return paytReason;
    }

    /**
     * Sets the value of the paytReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaytReason(String value) {
        this.paytReason = value;
    }

    /**
     * Gets the value of the taxPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxPeriod() {
        return taxPeriod;
    }

    /**
     * Sets the value of the taxPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxPeriod(String value) {
        this.taxPeriod = value;
    }

    /**
     * Gets the value of the docNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocNo() {
        return docNo;
    }

    /**
     * Sets the value of the docNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocNo(String value) {
        this.docNo = value;
    }

    /**
     * Gets the value of the docDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocDate() {
        return docDate;
    }

    /**
     * Sets the value of the docDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocDate(String value) {
        this.docDate = value;
    }

    /**
     * Gets the value of the taxPaytKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxPaytKind() {
        return taxPaytKind;
    }

    /**
     * Sets the value of the taxPaytKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxPaytKind(String value) {
        this.taxPaytKind = value;
    }

}
