//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 04:08:48 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocIDType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="DocIDType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}IdentifierTextCategory"&gt;
 *     &lt;enumeration value="DECLREF"/&gt;
 *     &lt;enumeration value="LETTER"/&gt;
 *     &lt;enumeration value="MEMO"/&gt;
 *     &lt;enumeration value="SWIFT"/&gt;
 *     &lt;enumeration value="UNDEF"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DocIDType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum DocIDType {

    DECLREF,
    LETTER,
    MEMO,
    SWIFT,
    UNDEF;

    public String value() {
        return name();
    }

    public static DocIDType fromValue(String v) {
        return valueOf(v);
    }

}
