//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 04:08:48 PM YEKT 
//


package com.sankdev.edbind;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Payment Order for a total amount with the register (transaction bulk)
 * 
 * <p>Java class for ED108 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ED108"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:cbr-ru:ed:v2.0}ED101"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CreditTransferTransactionInfo" type="{urn:cbr-ru:ed:v2.0}CreditTransferTransactionInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ED108", propOrder = {
    "creditTransferTransactionInfo"
})
public class ED108
    extends ED101
{

    @XmlElement(name = "CreditTransferTransactionInfo")
    protected List<CreditTransferTransactionInfo> creditTransferTransactionInfo;

    /**
     * Gets the value of the creditTransferTransactionInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the creditTransferTransactionInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditTransferTransactionInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditTransferTransactionInfo }
     * 
     * 
     */
    public List<CreditTransferTransactionInfo> getCreditTransferTransactionInfo() {
        if (creditTransferTransactionInfo == null) {
            creditTransferTransactionInfo = new ArrayList<CreditTransferTransactionInfo>();
        }
        return this.creditTransferTransactionInfo;
    }

}
