//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EMInfoType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EMInfoType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="INF1"/&gt;
 *     &lt;enumeration value="INF2"/&gt;
 *     &lt;enumeration value="INF3"/&gt;
 *     &lt;enumeration value="INF4"/&gt;
 *     &lt;enumeration value="INF5"/&gt;
 *     &lt;enumeration value="INF6"/&gt;
 *     &lt;enumeration value="INF7"/&gt;
 *     &lt;enumeration value="INF8"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EMInfoType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum EMInfoType {

    @XmlEnumValue("INF1")
    INF_1("INF1"),
    @XmlEnumValue("INF2")
    INF_2("INF2"),
    @XmlEnumValue("INF3")
    INF_3("INF3"),
    @XmlEnumValue("INF4")
    INF_4("INF4"),
    @XmlEnumValue("INF5")
    INF_5("INF5"),
    @XmlEnumValue("INF6")
    INF_6("INF6"),
    @XmlEnumValue("INF7")
    INF_7("INF7"),
    @XmlEnumValue("INF8")
    INF_8("INF8");
    private final String value;

    EMInfoType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EMInfoType fromValue(String v) {
        for (EMInfoType c: EMInfoType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
