//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 04:08:48 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Комплексный тип для электронных сообщений. Содержит реквизит EDSender.
 * 
 * <p>Java class for ESWithEDSender complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ESWithEDSender"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:cbr-ru:ed:v2.0}ESWithMandatoryEDReceiver"&gt;
 *       &lt;attribute name="EDSender" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}EDDrawerIDType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ESWithEDSender")
public class ESWithEDSender
    extends ESWithMandatoryEDReceiver
{

    @XmlAttribute(name = "EDSender", required = true)
    protected String edSender;

    /**
     * Gets the value of the edSender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEDSender() {
        return edSender;
    }

    /**
     * Sets the value of the edSender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEDSender(String value) {
        this.edSender = value;
    }

}
