//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FPSOperationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="FPSOperationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="INSR"/&gt;
 *     &lt;enumeration value="DELT"/&gt;
 *     &lt;enumeration value="UPDT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FPSOperationType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum FPSOperationType {


    /**
     * Добавить запись в таблицу (INSERT).
     * 
     */
    INSR,

    /**
     * Удалить запись из таблицы (DELETE).
     * 
     */
    DELT,

    /**
     * Изменить запись в таблице (UPDATE).
     * 
     */
    UPDT;

    public String value() {
        return name();
    }

    public static FPSOperationType fromValue(String v) {
        return valueOf(v);
    }

}
