//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Информация по запросу потранзакционного реестра.
 * 
 * <p>Java class for FPSRequestInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPSRequestInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="DateTimeInterval" type="{urn:cbr-ru:ed:v2.0}DateTimeInterval"/&gt;
 *         &lt;element name="BusinessDay" type="{urn:cbr-ru:ed:v2.0}BusinessDay"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="BIC" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}BICRUIDType" /&gt;
 *       &lt;attribute name="CorrespAcc" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}AccountNumberRUIDType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPSRequestInfoType", propOrder = {
    "dateTimeInterval",
    "businessDay"
})
public class FPSRequestInfoType {

    @XmlElement(name = "DateTimeInterval")
    protected DateTimeInterval dateTimeInterval;
    @XmlElement(name = "BusinessDay")
    protected BusinessDay businessDay;
    @XmlAttribute(name = "BIC", required = true)
    protected String bic;
    @XmlAttribute(name = "CorrespAcc", required = true)
    protected String correspAcc;

    /**
     * Gets the value of the dateTimeInterval property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeInterval }
     *     
     */
    public DateTimeInterval getDateTimeInterval() {
        return dateTimeInterval;
    }

    /**
     * Sets the value of the dateTimeInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeInterval }
     *     
     */
    public void setDateTimeInterval(DateTimeInterval value) {
        this.dateTimeInterval = value;
    }

    /**
     * Gets the value of the businessDay property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessDay }
     *     
     */
    public BusinessDay getBusinessDay() {
        return businessDay;
    }

    /**
     * Sets the value of the businessDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessDay }
     *     
     */
    public void setBusinessDay(BusinessDay value) {
        this.businessDay = value;
    }

    /**
     * Gets the value of the bic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIC() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIC(String value) {
        this.bic = value;
    }

    /**
     * Gets the value of the correspAcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrespAcc() {
        return correspAcc;
    }

    /**
     * Sets the value of the correspAcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrespAcc(String value) {
        this.correspAcc = value;
    }

}
