//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 04:08:48 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Fields 25-29 (Free attributes).
 * 
 * <p>Java class for FreeFieldsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FreeFieldsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Field25" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max2TextType" /&gt;
 *       &lt;attribute name="Field26" type="{urn:cbr-ru:ed:leaftypes:v2.0}CashDocIDType" /&gt;
 *       &lt;attribute name="Field27" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max10TextType" /&gt;
 *       &lt;attribute name="Field28" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max35TextType" /&gt;
 *       &lt;attribute name="Field29" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max35TextType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FreeFieldsType")
public class FreeFieldsType {

    @XmlAttribute(name = "Field25")
    protected String field25;
    @XmlAttribute(name = "Field26")
    protected String field26;
    @XmlAttribute(name = "Field27")
    protected String field27;
    @XmlAttribute(name = "Field28")
    protected String field28;
    @XmlAttribute(name = "Field29")
    protected String field29;

    /**
     * Gets the value of the field25 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField25() {
        return field25;
    }

    /**
     * Sets the value of the field25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField25(String value) {
        this.field25 = value;
    }

    /**
     * Gets the value of the field26 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField26() {
        return field26;
    }

    /**
     * Sets the value of the field26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField26(String value) {
        this.field26 = value;
    }

    /**
     * Gets the value of the field27 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField27() {
        return field27;
    }

    /**
     * Sets the value of the field27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField27(String value) {
        this.field27 = value;
    }

    /**
     * Gets the value of the field28 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField28() {
        return field28;
    }

    /**
     * Sets the value of the field28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField28(String value) {
        this.field28 = value;
    }

    /**
     * Gets the value of the field29 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField29() {
        return field29;
    }

    /**
     * Sets the value of the field29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField29(String value) {
        this.field29 = value;
    }

}
