//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 04:08:48 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FTIGroupCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="FTIGroupCodeType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}CodeCategory"&gt;
 *     &lt;enumeration value="CND1"/&gt;
 *     &lt;enumeration value="CND2"/&gt;
 *     &lt;enumeration value="INTR"/&gt;
 *     &lt;enumeration value="QWRH"/&gt;
 *     &lt;enumeration value="QWAP"/&gt;
 *     &lt;enumeration value="QSPC"/&gt;
 *     &lt;enumeration value="QWCH"/&gt;
 *     &lt;enumeration value="QWEC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FTIGroupCodeType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum FTIGroupCodeType {

    @XmlEnumValue("CND1")
    CND_1("CND1"),
    @XmlEnumValue("CND2")
    CND_2("CND2"),
    INTR("INTR"),
    QWRH("QWRH"),
    QWAP("QWAP"),
    QSPC("QSPC"),
    QWCH("QWCH"),
    QWEC("QWEC");
    private final String value;

    FTIGroupCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FTIGroupCodeType fromValue(String v) {
        for (FTIGroupCodeType c: FTIGroupCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
