//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Guarantee fund information.
 * 
 * <p>Java class for GarFunds complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GarFunds"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GarFundNumber" type="{urn:cbr-ru:ed:v2.0}GarFundNumber" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="GarFundsUsage" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}GarFundsUsageType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GarFunds", propOrder = {
    "garFundNumber"
})
public class GarFunds {

    @XmlElement(name = "GarFundNumber")
    protected GarFundNumber garFundNumber;
    @XmlAttribute(name = "GarFundsUsage", required = true)
    protected GarFundsUsageType garFundsUsage;

    /**
     * Gets the value of the garFundNumber property.
     * 
     * @return
     *     possible object is
     *     {@link GarFundNumber }
     *     
     */
    public GarFundNumber getGarFundNumber() {
        return garFundNumber;
    }

    /**
     * Sets the value of the garFundNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link GarFundNumber }
     *     
     */
    public void setGarFundNumber(GarFundNumber value) {
        this.garFundNumber = value;
    }

    /**
     * Gets the value of the garFundsUsage property.
     * 
     * @return
     *     possible object is
     *     {@link GarFundsUsageType }
     *     
     */
    public GarFundsUsageType getGarFundsUsage() {
        return garFundsUsage;
    }

    /**
     * Sets the value of the garFundsUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link GarFundsUsageType }
     *     
     */
    public void setGarFundsUsage(GarFundsUsageType value) {
        this.garFundsUsage = value;
    }

}
