//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 04:08:48 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LimitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="LimitType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}CodeCategory"&gt;
 *     &lt;enumeration value="FIPL"/&gt;
 *     &lt;enumeration value="FPML"/&gt;
 *     &lt;enumeration value="ICLL"/&gt;
 *     &lt;enumeration value="IOCL"/&gt;
 *     &lt;enumeration value="IPCL"/&gt;
 *     &lt;enumeration value="NURL"/&gt;
 *     &lt;enumeration value="TCLL"/&gt;
 *     &lt;enumeration value="URGL"/&gt;
 *     &lt;enumeration value="VIPL"/&gt;
 *     &lt;enumeration value="VPML"/&gt;
 *     &lt;enumeration value="IPIL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LimitType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum LimitType {

    FIPL,
    FPML,
    ICLL,
    IOCL,
    IPCL,
    NURL,
    TCLL,
    URGL,
    VIPL,
    VPML,
    IPIL;

    public String value() {
        return name();
    }

    public static LimitType fromValue(String v) {
        return valueOf(v);
    }

}
