//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Дополнительная информация по операции.
 * 
 * <p>Java class for OpRevaluationInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpRevaluationInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OpPreciousMetal" type="{urn:cbr-ru:ed:v2.0}OpPreciousMetal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpRevaluationInfo", propOrder = {
    "opPreciousMetal"
})
public class OpRevaluationInfo {

    @XmlElement(name = "OpPreciousMetal", required = true)
    protected OpPreciousMetal opPreciousMetal;

    /**
     * Gets the value of the opPreciousMetal property.
     * 
     * @return
     *     possible object is
     *     {@link OpPreciousMetal }
     *     
     */
    public OpPreciousMetal getOpPreciousMetal() {
        return opPreciousMetal;
    }

    /**
     * Sets the value of the opPreciousMetal property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpPreciousMetal }
     *     
     */
    public void setOpPreciousMetal(OpPreciousMetal value) {
        this.opPreciousMetal = value;
    }

}
