//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Реквизиты получателя
 * 
 * <p>Java class for PayeeInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayeeInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MaxPaytSum" type="{urn:cbr-ru:ed:v2.0}SumWithUnlimit" minOccurs="0"/&gt;
 *         &lt;element name="TotalPaytsSum" type="{urn:cbr-ru:ed:v2.0}SumWithUnlimit" minOccurs="0"/&gt;
 *         &lt;element name="PayeeAccInfo" type="{urn:cbr-ru:ed:v2.0}PayeeAccInfo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="PayeeBIC" type="{urn:cbr-ru:ed:leaftypes:v2.0}BICRUIDType" /&gt;
 *       &lt;attribute name="PayeeUIS" type="{urn:cbr-ru:ed:leaftypes:v2.0}EDDrawerIDType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayeeInfo", propOrder = {
    "maxPaytSum",
    "totalPaytsSum",
    "payeeAccInfo"
})
public class PayeeInfo {

    @XmlElement(name = "MaxPaytSum")
    protected SumWithUnlimit maxPaytSum;
    @XmlElement(name = "TotalPaytsSum")
    protected SumWithUnlimit totalPaytsSum;
    @XmlElement(name = "PayeeAccInfo")
    protected List<PayeeAccInfo> payeeAccInfo;
    @XmlAttribute(name = "PayeeBIC")
    protected String payeeBIC;
    @XmlAttribute(name = "PayeeUIS")
    protected String payeeUIS;

    /**
     * Gets the value of the maxPaytSum property.
     * 
     * @return
     *     possible object is
     *     {@link SumWithUnlimit }
     *     
     */
    public SumWithUnlimit getMaxPaytSum() {
        return maxPaytSum;
    }

    /**
     * Sets the value of the maxPaytSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link SumWithUnlimit }
     *     
     */
    public void setMaxPaytSum(SumWithUnlimit value) {
        this.maxPaytSum = value;
    }

    /**
     * Gets the value of the totalPaytsSum property.
     * 
     * @return
     *     possible object is
     *     {@link SumWithUnlimit }
     *     
     */
    public SumWithUnlimit getTotalPaytsSum() {
        return totalPaytsSum;
    }

    /**
     * Sets the value of the totalPaytsSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link SumWithUnlimit }
     *     
     */
    public void setTotalPaytsSum(SumWithUnlimit value) {
        this.totalPaytsSum = value;
    }

    /**
     * Gets the value of the payeeAccInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the payeeAccInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayeeAccInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayeeAccInfo }
     * 
     * 
     */
    public List<PayeeAccInfo> getPayeeAccInfo() {
        if (payeeAccInfo == null) {
            payeeAccInfo = new ArrayList<PayeeAccInfo>();
        }
        return this.payeeAccInfo;
    }

    /**
     * Gets the value of the payeeBIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeBIC() {
        return payeeBIC;
    }

    /**
     * Sets the value of the payeeBIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeBIC(String value) {
        this.payeeBIC = value;
    }

    /**
     * Gets the value of the payeeUIS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeUIS() {
        return payeeUIS;
    }

    /**
     * Sets the value of the payeeUIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeUIS(String value) {
        this.payeeUIS = value;
    }

}
