//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Additional information for “Pending deletion” restriction.
 * 
 * <p>Java class for PendingDeletionInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PendingDeletionInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DestinationInfo" type="{urn:cbr-ru:ed:v2.0}DestinationInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="AccountCloseDate" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}DateType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PendingDeletionInfo", propOrder = {
    "destinationInfo"
})
public class PendingDeletionInfo {

    @XmlElement(name = "DestinationInfo")
    protected DestinationInfo destinationInfo;
    @XmlAttribute(name = "AccountCloseDate", required = true)
    protected XMLGregorianCalendar accountCloseDate;

    /**
     * Gets the value of the destinationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationInfo }
     *     
     */
    public DestinationInfo getDestinationInfo() {
        return destinationInfo;
    }

    /**
     * Sets the value of the destinationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationInfo }
     *     
     */
    public void setDestinationInfo(DestinationInfo value) {
        this.destinationInfo = value;
    }

    /**
     * Gets the value of the accountCloseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccountCloseDate() {
        return accountCloseDate;
    }

    /**
     * Sets the value of the accountCloseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccountCloseDate(XMLGregorianCalendar value) {
        this.accountCloseDate = value;
    }

}
