//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.21 at 04:08:48 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PerfomanceSchemaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="PerfomanceSchemaType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}IdentifierTextCategory"&gt;
 *     &lt;enumeration value="AONS"/&gt;
 *     &lt;enumeration value="INDS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PerfomanceSchemaType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum PerfomanceSchemaType {

    AONS,
    INDS;

    public String value() {
        return name();
    }

    public static PerfomanceSchemaType fromValue(String v) {
        return valueOf(v);
    }

}
