//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="QueueType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}CodeCategory"&gt;
 *     &lt;enumeration value="QINT"/&gt;
 *     &lt;enumeration value="QSPC"/&gt;
 *     &lt;enumeration value="QWAP"/&gt;
 *     &lt;enumeration value="QWCH"/&gt;
 *     &lt;enumeration value="QWRH"/&gt;
 *     &lt;enumeration value="QWEC"/&gt;
 *     &lt;enumeration value="QWAC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "QueueType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum QueueType {

    QINT,
    QSPC,
    QWAP,
    QWCH,
    QWRH,
    QWEC,
    QWAC;

    public String value() {
        return name();
    }

    public static QueueType fromValue(String v) {
        return valueOf(v);
    }

}
