//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReasonCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="ReasonCodeType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}CodeCategory"&gt;
 *     &lt;enumeration value="ACCH"/&gt;
 *     &lt;enumeration value="AICH"/&gt;
 *     &lt;enumeration value="ALCH"/&gt;
 *     &lt;enumeration value="ANTC"/&gt;
 *     &lt;enumeration value="APPA"/&gt;
 *     &lt;enumeration value="RIRA"/&gt;
 *     &lt;enumeration value="RIRP"/&gt;
 *     &lt;enumeration value="RMAA"/&gt;
 *     &lt;enumeration value="RMVA"/&gt;
 *     &lt;enumeration value="RQST"/&gt;
 *     &lt;enumeration value="SMON"/&gt;
 *     &lt;enumeration value="SOBD"/&gt;
 *     &lt;enumeration value="SPOF"/&gt;
 *     &lt;enumeration value="UIRA"/&gt;
 *     &lt;enumeration value="UIRP"/&gt;
 *     &lt;enumeration value="ARRD"/&gt;
 *     &lt;enumeration value="ARRM"/&gt;
 *     &lt;enumeration value="ARRS"/&gt;
 *     &lt;enumeration value="EOBD"/&gt;
 *     &lt;enumeration value="EOCC"/&gt;
 *     &lt;enumeration value="ICLD"/&gt;
 *     &lt;enumeration value="ICLM"/&gt;
 *     &lt;enumeration value="ICLS"/&gt;
 *     &lt;enumeration value="PCHD"/&gt;
 *     &lt;enumeration value="CSCH"/&gt;
 *     &lt;enumeration value="NSCH"/&gt;
 *     &lt;enumeration value="FCBD"/&gt;
 *     &lt;enumeration value="CIBD"/&gt;
 *     &lt;enumeration value="PPAD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ReasonCodeType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum ReasonCodeType {

    ACCH,
    AICH,
    ALCH,
    ANTC,
    APPA,
    RIRA,
    RIRP,
    RMAA,
    RMVA,
    RQST,
    SMON,
    SOBD,
    SPOF,
    UIRA,
    UIRP,
    ARRD,
    ARRM,
    ARRS,
    EOBD,
    EOCC,
    ICLD,
    ICLM,
    ICLS,
    PCHD,
    CSCH,
    NSCH,
    FCBD,
    CIBD,
    PPAD;

    public String value() {
        return name();
    }

    public static ReasonCodeType fromValue(String v) {
        return valueOf(v);
    }

}
