//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RstrType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="RstrType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}IdentifierTextCategory"&gt;
 *     &lt;enumeration value="NORS"/&gt;
 *     &lt;enumeration value="URRS"/&gt;
 *     &lt;enumeration value="LWRS"/&gt;
 *     &lt;enumeration value="LMRS"/&gt;
 *     &lt;enumeration value="CLRS"/&gt;
 *     &lt;enumeration value="FPRS"/&gt;
 *     &lt;enumeration value="MRTR"/&gt;
 *     &lt;enumeration value="SDRS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RstrType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum RstrType {

    NORS,
    URRS,
    LWRS,
    LMRS,
    CLRS,
    FPRS,
    MRTR,
    SDRS;

    public String value() {
        return name();
    }

    public static RstrType fromValue(String v) {
        return valueOf(v);
    }

}
