//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 12:23:07 PM YEKT 
//


package com.sankdev.edbind;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Payment Settlement Condition Attributes.
 * 
 * <p>Java class for SettlementCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SettlementCondition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="LiquidityReservationSchemeParameters" type="{urn:cbr-ru:ed:v2.0}LiquidityReservationSchemeParameters"/&gt;
 *         &lt;element name="CoverFundsSchemeParameters" type="{urn:cbr-ru:ed:v2.0}CoverFundsSchemeParameters"/&gt;
 *         &lt;element name="RCPSchemeParameters" type="{urn:cbr-ru:ed:v2.0}RCPSchemeParameters"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="ConditionCode" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}ConditionCodeType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SettlementCondition", propOrder = {
    "liquidityReservationSchemeParameters",
    "coverFundsSchemeParameters",
    "rcpSchemeParameters"
})
public class SettlementCondition {

    @XmlElement(name = "LiquidityReservationSchemeParameters")
    protected LiquidityReservationSchemeParameters liquidityReservationSchemeParameters;
    @XmlElement(name = "CoverFundsSchemeParameters")
    protected CoverFundsSchemeParameters coverFundsSchemeParameters;
    @XmlElement(name = "RCPSchemeParameters")
    protected RCPSchemeParameters rcpSchemeParameters;
    @XmlAttribute(name = "ConditionCode", required = true)
    protected ConditionCodeType conditionCode;

    /**
     * Gets the value of the liquidityReservationSchemeParameters property.
     * 
     * @return
     *     possible object is
     *     {@link LiquidityReservationSchemeParameters }
     *     
     */
    public LiquidityReservationSchemeParameters getLiquidityReservationSchemeParameters() {
        return liquidityReservationSchemeParameters;
    }

    /**
     * Sets the value of the liquidityReservationSchemeParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link LiquidityReservationSchemeParameters }
     *     
     */
    public void setLiquidityReservationSchemeParameters(LiquidityReservationSchemeParameters value) {
        this.liquidityReservationSchemeParameters = value;
    }

    /**
     * Gets the value of the coverFundsSchemeParameters property.
     * 
     * @return
     *     possible object is
     *     {@link CoverFundsSchemeParameters }
     *     
     */
    public CoverFundsSchemeParameters getCoverFundsSchemeParameters() {
        return coverFundsSchemeParameters;
    }

    /**
     * Sets the value of the coverFundsSchemeParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverFundsSchemeParameters }
     *     
     */
    public void setCoverFundsSchemeParameters(CoverFundsSchemeParameters value) {
        this.coverFundsSchemeParameters = value;
    }

    /**
     * Gets the value of the rcpSchemeParameters property.
     * 
     * @return
     *     possible object is
     *     {@link RCPSchemeParameters }
     *     
     */
    public RCPSchemeParameters getRCPSchemeParameters() {
        return rcpSchemeParameters;
    }

    /**
     * Sets the value of the rcpSchemeParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link RCPSchemeParameters }
     *     
     */
    public void setRCPSchemeParameters(RCPSchemeParameters value) {
        this.rcpSchemeParameters = value;
    }

    /**
     * Gets the value of the conditionCode property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionCodeType }
     *     
     */
    public ConditionCodeType getConditionCode() {
        return conditionCode;
    }

    /**
     * Sets the value of the conditionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionCodeType }
     *     
     */
    public void setConditionCode(ConditionCodeType value) {
        this.conditionCode = value;
    }

}
